# Generated by Django 4.2.1 on 2023-05-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images', verbose_name='Banner Image')),
                ('title', models.CharField(max_length=150, verbose_name='Banner Title')),
                ('text', models.CharField(max_length=150, verbose_name='Banner Text')),
            ],
        ),
    ]
