# Generated by Django 4.2.1 on 2023-05-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pt_1', models.CharField(max_length=50, verbose_name='Title part 1')),
                ('pt_2', models.CharField(max_length=50, verbose_name='Title part 2')),
            ],
        ),
    ]
