# Generated by Django 4.2.1 on 2023-05-12 18:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_sitetitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images', verbose_name='Product Image')),
                ('title', models.TextField(max_length=50, verbose_name='Product Title')),
                ('price', models.FloatField(verbose_name='Product price')),
                ('text', models.TextField(max_length=60, verbose_name='Product')),
                ('reviews_count', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
