# Generated by Django 4.2.1 on 2023-05-12 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='reviews_count',
            new_name='reviews',
        ),
    ]
