# Generated by Django 4.2.1 on 2023-05-13 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_productscategory_products_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homebanner',
            options={'verbose_name': 'Home Banner', 'verbose_name_plural': 'Home Banners'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productscategory',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='sitetitle',
            options={'verbose_name': 'Site Title', 'verbose_name_plural': 'Site Title'},
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='main.productscategory'),
        ),
        migrations.AlterField(
            model_name='products',
            name='text',
            field=models.TextField(max_length=60, verbose_name='Text'),
        ),
    ]
