# Generated by Django 4.2.1 on 2023-05-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_homebanner_options_alter_products_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeppyCustomers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='', verbose_name='Customer Image')),
            ],
            options={
                'verbose_name': 'Heppy Customer',
                'verbose_name_plural': 'Heppy Customers',
            },
        ),
    ]
