# Generated by Django 4.2.1 on 2023-05-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_pages_banners'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('text_1', models.TextField(verbose_name='Text 1')),
                ('text_2', models.TextField(verbose_name='Text 2')),
                ('map_url', models.URLField(default='', verbose_name='Map Url')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook Url')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter Url')),
                ('linked_in_url', models.URLField(blank=True, verbose_name='Linked in Url')),
                ('be_url', models.URLField(blank=True, verbose_name='Be Url')),
            ],
            options={
                'verbose_name': 'Our Background',
                'verbose_name_plural': 'Our Background',
            },
        ),
    ]
