# Generated by Django 4.2.1 on 2023-05-13 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_ourbackground_map_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourbackground',
            name='img',
            field=models.ImageField(default='', upload_to='', verbose_name='Image'),
        ),
    ]
