# Generated by Django 4.2.1 on 2023-05-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_ourbackground_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Member Name')),
                ('profession', models.CharField(max_length=100, verbose_name='Member Profession')),
                ('about', models.TextField(verbose_name='About Member')),
                ('img', models.ImageField(upload_to='images', verbose_name='Member Photo')),
                ('linkedin', models.URLField(blank=True, verbose_name='Linkedin URL')),
                ('fb', models.URLField(blank=True, verbose_name='facebook URL')),
                ('twitter', models.URLField(blank=True, verbose_name='twitter URL')),
                ('be', models.URLField(blank=True, verbose_name='behance URL')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
            },
        ),
    ]
