# Generated by Django 4.2.1 on 2023-05-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSixtennClothingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'About Sixtenn Clothing List',
                'verbose_name_plural': 'About Sixtenn Clothing List',
            },
        ),
        migrations.CreateModel(
            name='AboutSixtennClothing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('ul', models.ManyToManyField(to='main.aboutsixtennclothinglist')),
            ],
            options={
                'verbose_name': 'About Sixtenn Clothing',
                'verbose_name_plural': 'About Sixtenn Clothing',
            },
        ),
    ]
