# Generated by Django 4.2.1 on 2023-05-13 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0003_alter_aboutofice_options_alter_accordion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutofice',
            options={'verbose_name': 'About Ofice', 'verbose_name_plural': 'About Ofice'},
        ),
    ]
